name: dev_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  flutter_lints: ^3.0.0
  share_plus: ^12.0.1
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  http: ^1.2.2
  audioplayers: ^6.1.0
  qr_flutter: ^4.1.0
  pdf: ^3.11.0
  image: ^4.2.0
  pasteboard: ^0.2.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

# Configuration to maximize the icon size
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  # Reducing inset to 0 makes it fill the 200dp safe zone completely
  adaptive_icon_foreground_inset: 0
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  # Force high-res generation
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sounds/scan_beep.wav
    - assets/sounds/scan_chirp.wav
    - assets/sounds/scan_tick.wav
