name: dev_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  flutter_lints: ^6.0.0
  share_plus: ^12.0.1
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

# Configuration for flutter_launcher_icons (top-level, not nested)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
